---
name: CI workflow
"on": [push]
env:
  CFLAGS: -fdiagnostics-color
jobs:
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: install-deps
        run: |
          sudo apt-get update
          sudo apt install -y libunwind-dev
          sudo apt-get -y install \
            gettext \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-good \
            gstreamer1.0-tools \
            libgoocanvas-2.0-dev \
            libgspell-1-dev \
            libgstreamer1.0-dev \
            libgtksourceview-4-dev \
            libhandy-1-dev \
            libplist-dev \
            libwebkit2gtk-4.1-dev \
            libxml2-utils \
            meson \
            ninja-build

      - uses: actions/checkout@v4

      # Make fake Inform binaries so we don't have to download and build them
      # just to run the UI tests
      - name: create-fake-inform7-data
        run: |
          mkdir intools
          touch intools/{inform6,inblorb}
          echo >intools/inform7 '#!/bin/sh'
          echo >>intools/inform7 "echo \"inform7 version 10.1.2 'Krypton' (29 August 2022)\""
          chmod a+x intools/inform7
          mkdir -p retrospective/6{L02,L38,M62}
          touch retrospective/6{L02,L38,M62}/ni
          touch retrospective/6{L02,L38,M62}/cBlorb
          touch retrospective/retrospective.txt

      - name: configure
        run: meson _build

      - name: build
        run: ninja -C _build

      - name: test
        run: xvfb-run -a meson test -C _build
