---
name: Build packages
"on":
  push:
    branches: [main]
jobs:
  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          branch: main
          bundle: inform7-flatpak.flatpak
          manifest-path: build-aux/com.inform7.IDE.yml

  download-ni:
    name: Download NI
    runs-on: ubuntu-latest
    steps:
      - name: cache-ni
        id: cache-ni
        uses: actions/cache@v2
        with:
          path: I7_6M62_Linux_all.tar.gz
          key: download-6M62-20220313.2
          restore-keys: download-6M62

      - name: download-ni
        if: steps.cache-ni.outputs.cache-hit != 'true'
        run: curl -O "http://inform7.com/apps/6M62/I7_6M62_Linux_all.tar.gz"

  rpm:
    name: RPM
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:35
    needs: download-ni
    env:
      # harmless /usr/lib64 rpath in inform7-ide binary; not sure what from
      QA_RPATHS: '1'
    steps:
      # restoring the cache silently fails without zstd
      - name: install-deps
        run: |
          dnf install -y \
            gcc \
            gettext \
            git \
            glib2-devel \
            goocanvas2-devel \
            gspell-devel \
            gstreamer1-devel \
            gstreamer1-plugins-bad-free \
            gstreamer1-plugins-bad-free-extras \
            gstreamer1-plugins-base \
            gstreamer1-plugins-good \
            gtk3-devel \
            gtksourceview4-devel \
            libplist-devel \
            jq \
            meson \
            rpm-build \
            webkit2gtk3-devel \
            wget \
            xz-lzma-compat \
            zstd

      - uses: actions/checkout@v2

      - name: restore-cache
        uses: actions/cache@v2
        with:
          path: I7_6M62_Linux_all.tar.gz
          key: download-6M62

      - name: copy-and-unpack-ni
        run: |
          mkdir -p /github/home/rpmbuild/SOURCES/
          cp I7_6M62_Linux_all.tar.gz /github/home/rpmbuild/SOURCES/
          tar xzf I7_6M62_Linux_all.tar.gz
          tar -f inform7-6M62/inform7-compilers_6M62_x86_64.tar.gz  -C src/ni/ \
            -x share/inform7/Compilers/ni --strip-components=3

      - name: configure
        run: meson _build

      - name: package-tarball
        run: meson dist -C _build --no-tests --include-subprojects

      - name: build-rpm
        run: build-aux/build-rpm.sh _build

      - uses: actions/upload-artifact@v1
        with:
          name: RPM package
          path: inform7-ide-2.0.0-1.fc35.x86_64.rpm

  deb:
    name: Debian
    runs-on: ubuntu-latest
    needs: download-ni
    steps:
      - name: install-deps
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            debhelper \
            devscripts \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-tools \
            jq \
            libgoocanvas-2.0-dev \
            libgspell-1-dev \
            libgstreamer1.0-dev \
            libgtk-3-dev \
            libgtksourceview-4-dev \
            libplist-dev \
            libwebkit2gtk-4.0-dev \
            libxml2-utils \
            meson

      - name: upgrade-meson
        run: |
          curl -O http://ftp.osuosl.org/pub/ubuntu/pool/universe/m/meson/meson_0.57.0+really0.56.2-0.1_all.deb
          sudo dpkg -i meson_0.57.0+really0.56.2-0.1_all.deb

      - uses: actions/checkout@v2

      - name: restore-cache
        uses: actions/cache@v2
        with:
          path: I7_6M62_Linux_all.tar.gz
          key: download-6M62

      - name: unpack-ni
        run: |
          tar xzf I7_6M62_Linux_all.tar.gz
          tar -f inform7-6M62/inform7-compilers_6M62_x86_64.tar.gz  -C src/ni/ \
            -x share/inform7/Compilers/ni --strip-components=3

      - name: configure
        run: meson _build

      - name: package-tarball
        run: meson dist -C _build --no-tests --include-subprojects

      - name: build-deb
        run: build-aux/build-deb.sh _build

      - uses: actions/upload-artifact@v1
        with:
          name: Debian package
          path: inform7-ide_2.0.0-1_amd64.deb
